### ISSUE TITLE
Would like to see generated Typescript definitions for ClarifaiStub

### ISSUE THREAD

**Issue by andrew-pyle** [Clarifai/clarifai-nodejs-grpc#13]
# It would be great to have Typescript definitions for this library, or at least for the `ClarifaiStub`

@rok-clarifai Thank you for this NodeJS Library! The Readme explains the basic "predict" functionality well.

I'm lost when it comes to working with the callback, though. Apart from inspecting test responses, it's not easy to determine what values are possible for the callback parameters. From the Readme:
```js
(err, response) => { // What is the type of err and response?
    if (err) {
        console.log("Error: " + err);
        return;
    }
    if (response.status.code !== 10000) {
        console.log("Received failed status: " + response.status.description + "\n" + response.status.details);
        return;
    }

    for (const c of response.outputs[0].data.concepts) {
        console.log(c.name + ": " + c.value);
    }
}
```

I am totally unfamiliar with gRPC, so I don't have any intuition about how this library behaves, so a `.d.ts` file would be extremely helpful.

I believe that it should be possible to automatically generate TS definitions for the `ClarifaiStub`, at least [this post seems to say so](https://medium.com/attest-r-and-d/fully-typed-typescript-api-consuming-grpc-and-graphql-5d5ae6b33bf1) in the section "Generating gRPC clients and types from proto files"

Is this something the authors can do?

**Comment by andrew-pyle** [comment]
[grpc_tools_node_protoc_ts](https://github.com/agreatfool/grpc_tools_node_protoc_ts) is a related tool.

**Comment by rok-povsic** [comment]
Hi @andrew-pyle thanks for the suggestion, we'll look at generating Typescript definitions - they would definitely be helpful.

To address your initial problem: the easiest way currently would be to observe the returned response objects directly (e.g. print them to std. out) and inspect what kind of structure they have. I agree it's not ideal. 

Alternatively, you could use the Clarifai API from one ouf our sister clients in a static language (Java, C#) where the response structure might be more clearly visible in an IDE.

**Comment by rok-clarifai** [comment]
@andrew-pyle In version 7.0.3 we've added TypeScript declaration files, making auto-completion in IDEs work really nicely. See the *The static approach* section in the [README](https://github.com/Clarifai/clarifai-nodejs-grpc).

**Comment by andrew-pyle** [comment]
Thank you for the Static Approach!

However, types are missing for `grpc` , which is re-exported from the `@grpc/grpc-js` dependency. I've proposed re-exporting the type definition of `grpc` as well in PR #19.
