### ISSUE TITLE
What breaking changes are in v7?

### ISSUE THREAD

**Issue by andrew-pyle** [Clarifai/clarifai-nodejs-grpc#15]
Thank you for the great new Typescript definitions in v7.

However, I can't find a Changelog or Release notes. What has changed in this library's API? What's new? Where will code consuming v6 break with v7?

**Comment by rok-clarifai** [comment]
Hello @andrew-pyle thanks for the questions, we should definitely add explanations to the repository.

This library doesn't follow semantic versioning. The version is attached to the API version (backend). Actually, this is the case only for the first two version number, e.g. **7.0**.1. The third number, e.g. 7.0.**1**, is available to this NodeJS library for any fixes and upgrades.

When the API got updated to 7.0, this library got a 7.0.0 release. The changes are described [here in the changelog](https://docs.clarifai.com/product-updates/changelog) but they don't include any major breaking changes.

In 7.0.3, this library was updated with a new feature -the "statically compiled" usage approach, which includes Typescript definitions (as explained in README). This was also not a breaking change, just another feature added and can be used in addition to the existing "dynamic" approach.
