### ISSUE TITLE
Importing non existing types from deprecated repo

### ISSUE THREAD

**Issue by lukasbm** [Clarifai/clarifai-nodejs-grpc#26]
in [this](https://github.com/Clarifai/clarifai-nodejs-grpc/blob/02edaf65129c04d8cf675f37dbc4aaab4b8cebfc/proto/clarifai/api/service_grpc_pb.d.ts#L7) line you import the types from `grpc`. But `grpc` is the deprecated version with not type declarations.

fix: `import * as grpc from "@grpc/grpc-js";`

**Comment by aleksander-clarifai** [comment]
Hello @lukasbm,

Thank you for your suggestion. Fix will be applied in the next version.

Best Regards,
Aleksander
