### ISSUE TITLE
get auth error "Empty or malformed authorization header. Please provide an API key or session token."

### ISSUE THREAD

**Issue by DisaPadla** [Clarifai/clarifai-nodejs-grpc#9]
Hi!
**Code example:**

```
const {ClarifaiStub} = require("clarifai-nodejs-grpc");
const grpc = require("@grpc/grpc-js");

const stub = ClarifaiStub.insecureGrpc();

const metadata = new grpc.Metadata();
metadata.set("authorization", "Key " + MY_API_KEY);

stub.PostModelOutputs(
      {
          model_id: 'ivp-model',
          inputs: [{data: {image: {url: 'https://samples.clarifai.com/food.jpg'}}}]
      },
      metadata,
      (err: any, response: any) => {
          if (err) {
              console.log("Error: " + err);
              return;
          }
  
          if (response.status.code !== 10000) {
              console.log("Received failed status: " + response.status.description + "\n" + response.status.details);
              return;
          }
  
          for (const c of response.outputs[0].data.concepts) {
              console.log(c.name + ": " + c.value);
          }
      }

```
**I always get:**
'Received failed status: Invalid request
Empty or malformed authorization header. Please provide an API key or session token.'

As I understood, I need to take MY_API_KEY from an application page on https://portal.clarifai.com/ in "API Keys" area.
What I do wrong?

**Comment by rok-clarifai** [comment]
Hi @DisaPadla sorry for late response. The code you pasted (with adding the ending `)` and removing the type hints) works for me after setting the `MY_API_KEY` to the actual Clarifai's API key.

**Comment by Pizzacus** [comment]
Hi, I have the same issue with this code:

```js
const {ClarifaiStub} = require('clarifai-nodejs-grpc');
const grpc = require('@grpc/grpc-js');

const stub = ClarifaiStub.insecureGrpc();

const metadata = new grpc.Metadata();
metadata.set('authorization', 'Key ' + MY_API_KEY);

stub.PostWorkflowResults(
	{
		workflow_id: 'General',
		inputs: [{data: {image: {url: 'https://samples.clarifai.com/food.jpg'}}}]
	},
	metadata,
	(err, response) => {
		if (err) {
			console.log('Error: ' + err);
			return;
		}

		if (response.status.code !== 10000) {
			console.log('Received failed status: ' + response.status.description + '\n' + response.status.details);
			return;
		}

		console.log(response);
	}
);
```

Output:
```
Received failed status: Invalid request
Empty or malformed authorization header. Please provide an API key or session token.
```

* I **really** double-checked the key was typed right, copied it with the copy button on the UI
* I tried making a new API key, just in case this only affected pretty old keys
* `"@grpc/grpc-js": "^1.1.7"`, `"clarifai-nodejs-grpc": "^6.8.0"`, and Node v14.12.0
* I'm on the community plan, still have usage left
* I have an application on the old unsupported `clarifai-javascript` lib, it uses the same API key and works fine. I was actually migrating it.

Although, many thanks for the sweet image labelling! ❤️

**Comment by rok-clarifai** [comment]
Strange. I tested both examples using Node 10, 12, 14 using a new Clarifai account with community plan, and I cannot reproduce this on Ubuntu 20.04 (using the currently latest clarifai-nodejs-grpc version `6.10.0`). I'm not sure what else I could check.

**Comment by rok-clarifai** [comment]
We've also tested this on Windows, macOS and Linux and cannot reproduce unfortunately.

If you'd be willing to setup a remote session so I can see the issue manifesting in your environment, please contact me at rok.povsic insertAThere clarifai.com

**Comment by rok-clarifai** [comment]
The issue should now be fixed, with the caveat that you need to require `grpc` from our library, not directly requiring `@grpc/grpc-js`.

So to fix the problem, upgrade this library to (at least) 7.0.2 and import `grpc` directly from the library, i.e.:
```javascript
const {ClarifaiStub, grpc} = require("clarifai-nodejs-grpc");
```

The issue manifested when having another library installed that has `@grpc/grpc-js` as a dependency as well (such as `firebase-admin`) and where the version differs from this library. Since the example code said to do `const grpc = require("@grpc/grpc-js")` directly,  this import could use the other instance, which doesn't work with `@grpc/grpc-js` for most (but not all) version pairs.

Please let me know if this works or you experience any more problems.
